---
k3s_kubectl_binary: k3s kubectl
longhorn_check_timeout: 360s
longhorn_chart_version: 1.7.1
longhorn_chart_repo: https://charts.longhorn.io
longhorn_chart_values:
  persistence:
    defaultClass: true
    defaultClassReplicaCount: 1
    defaultDataLocality: strict-local
    migratable: false
    reclaimPolicy: Delete
  networkPolicies:
    enabled: true
